export const LOADING_USERS = 'LOADING_USERS';
export const LOADING_USERS_SUCCESSFULLY = 'LOADING_USERS_SUCCESSFULLY';
export const LOADING_USERS_ERROR = 'LOADING_USERS_ERROR';

export const SIGNUP_USER = 'SIGNUP_USER' ;
export const SIGNUP_USERS_SUCCESSFULLY = 'SIGNUP_USERS_SUCCESSFULLY';
export const SIGNUP_USERS_ERROR = 'SIGNUP_USERS_ERROR';

export const LOGIN_USER = 'LOGIN_USER' ;
export const LOGIN_USERS_SUCCESSFULLY = 'LOGIN_USERS_SUCCESSFULLY';
export const LOGIN_USERS_ERROR = 'LOGIN_USERS_ERROR';
export const HIDE_ALERT = 'HIDE_ALERT';